### ISSUE TITLE
Confirmed  and recovered cases = 0 for no reason

### ISSUE THREAD

**Issue by ifndev** [ExpDev07/coronavirus-tracker-api#136] opened 2020-03-22 00:12 UTC
The number of confirmed and recovered cases are returning 0. 

For example:
>  https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=FR
`"latest":{"confirmed":0,"deaths":450,"recovered":0}`

Same problem for every country i tested, and for world statistics also... wasn't a problem an hour ago. 
Is it just me ?

EDIT: Seems to be related to the alst update (`2020-03-22T00:05:34.338735Z`)

**Comment by ifndev** [comment] 2020-03-22 00:15
seems related to #113

**Comment by LTapsy** [comment] 2020-03-22 00:16
Were also having the same problem. we currently using your data. please let us know how we can help.

**Comment by Benjozork** [comment] 2020-03-22 00:18
Can confirm

![image](https://user-images.githubusercontent.com/4503241/77239428-feb65600-6bb0-11ea-9e90-4412e7802593.png)

Let me know if you need any help !

**Comment by ExpDev07** [comment] 2020-03-22 00:24
It’s JHU adding 0 again to their latest update. Give it a few minutes and I’ll restart the server.

**Comment by tulsi-prasad** [comment] 2020-03-22 00:30
Yes, the data almost vanished totally. Thanks in advance for the fix, counting on it.

**Comment by Benjozork** [comment] 2020-03-22 00:39
JHU is becoming pretty unreliable with their data ...

**Comment by ExpDev07** [comment] 2020-03-22 00:43
Unfortunately, there are a few issues that always arise.

**Comment by Benjozork** [comment] 2020-03-22 01:12
I can confirmed the issue is now fixed for me.

**Closed** 2020-03-22 01:20 UTC

**Comment by LTapsy** [comment] 2020-03-22 01:30
Thank you!

**Comment by jonmancia** [comment] 2020-03-22 04:41
Unfortunately, it's back again. Any fix I could do on my end?

**Comment by ExpDev07** [comment] 2020-03-22 04:44
@jonmancia JHU has been showing U.S. recoveries at 0 for a day now (https://github.com/ExpDev07/coronavirus-tracker-api/issues/113). An issue was created about it here: https://github.com/CSSEGISandData/COVID-19/issues/1208.

**Comment by paolinic03** [comment] 2020-03-22 16:01
JHU needs to take their sources down from public use until they are fixed. They touted being #1 on github a week ago but don’t want to walk the walk.

**Comment by ifndev** [comment] 2020-05-05 17:31
Thanks !
